          seed = -1
       seqfile = ../../fus_nucl_dating10_mcmctree_short.phy
      treefile = ../fus_proteins_62T_iqtree_genepart.contree_rooted_blank_clocktest
      mcmcfile = mcmc.txt
       outfile = mcmctree_clocktest_out.txt
         ndata = 1
       usedata = 1    	 * 0: no data; 1:seq like; 2:use in.BV; 3: out.BV
         clock =     	 * 1: global clock; 2: independent rates; 3: correlated rates
         model = 4    	 * 0:JC69, 1:K80, 2:F81, 3:F84, 4:HKY85
         alpha = 0.5     * alpha for gamma rates at sites
         ncatG = 5    	 * No. categories in discrete gamma
     cleandata = 0    	 * remove sites with ambiguity data (1:yes, 0:no)?
       BDparas = 1 1 0   * birth, death, sampling
   kappa_gamma = 6 2
   alpha_gamma = 1 1
   rgene_gamma = 1 5   	 * gamma prior for overall rates for genes
  sigma2_gamma = 1 10    * gamma prior for sigma^2     (for clock=2 or 3)
         print = 1
        burnin = 2000
      sampfreq = 10
       nsample = 20000
