          seed = -1
       seqfile = fus_proteins_dating10_mcmctree_short.phy
      treefile = fus_proteins_62T_iqtree_genepart.treefile_rooted_blank
       outfile = mcmctree_step1_output.txt
         ndata = 10
       seqtype = 2  * 0: nucleotides; 1:codons; 2:AAs
       usedata = 3    * 0: no data; 1:seq like; 2:use in.BV; 3: out.BV
         clock = 2    * 1: global clock; 2: independent rates; 3: correlated rates
         model = 0    * 0:JC69, 1:K80, 2:F81, 3:F84, 4:HKY85
         alpha = 0    * alpha for gamma rates at sites
         ncatG = 5    * No. categories in discrete gamma
     cleandata = 0    * remove sites with ambiguity data (1:yes, 0:no)?
